"""Corpus-wide standards knowledge graph.

The graph is *derived*, never asserted. Every node is a stored ``Standard`` or
``QCO`` row, and every edge is a stored ``StandardRelationship`` (which itself
cites the clause that states the relationship) or a regulatory record. Nothing
here is generated by a model, so the graph can be trusted the same way the rest
of the corpus can.

This lives apart from the per-product graph in ``api/products.py``: that one is
scoped to a single product's matched standards, whereas this one lets a user
explore the whole ecosystem and, optionally, the neighbourhood of one standard.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

from pymongo import ASCENDING
from pymongo.database import Database

from app.core.text_utils import display_is_number
from app.db.repositories import clauses as clauses_repo
from app.db.repositories import relationships as relationships_repo
from app.db.repositories import requirements as requirements_repo
from app.db.repositories import standards as standards_repo
from app.models import Standard, StandardRelationship
from app.services.regulatory import resolve_regulatory_status


def _display_number(standard: Standard) -> str:
    return display_is_number(standard.normalized_number) or standard.is_number

#: Human wording + a one-line explanation for each relationship type the corpus
#: uses. Anything not listed still renders, falling back to a titled label.
RELATIONSHIP_META: Dict[str, Dict[str, str]] = {
    "references_safety_standard": {
        "label": "references safety standard",
        "description": "The source standard names the target as a normative reference for general safety.",
    },
    "references_test_method": {
        "label": "references test method",
        "description": "The source standard defers to the target for a test procedure.",
    },
    "references_marking_standard": {
        "label": "references marking standard",
        "description": "The source standard names the target for marking, labelling and instructions.",
    },
    "companion_part": {
        "label": "companion part",
        "description": "The two standards are parts of the same multi-part series.",
    },
    "amended_by": {
        "label": "amended by",
        "description": "The target amends the source.",
    },
    "superseded_by": {
        "label": "superseded by",
        "description": "The target replaces the source.",
    },
    "regulated_by": {
        "label": "regulated by",
        "description": "A Quality Control Order makes conformity to this standard mandatory.",
    },
}


def _rel_label(rel_type: str) -> str:
    meta = RELATIONSHIP_META.get(rel_type)
    if meta:
        return meta["label"]
    return rel_type.replace("_", " ")


class StandardsGraphService:
    """Build the corpus-wide standards graph from stored records only."""

    def build(
        self,
        db: Database,
        *,
        category: str = "",
        focus: str = "",
        include_regulatory: bool = True,
    ) -> Dict[str, Any]:
        standards = self._select_standards(db, category=category, focus=focus)
        standard_ids = {s.id for s in standards}

        nodes: List[Dict[str, Any]] = []
        edges: List[Dict[str, Any]] = []
        node_ids: set[str] = set()

        # ---- Standard nodes -------------------------------------------------
        regulatory_by_standard: Dict[str, Any] = {}
        for standard in standards:
            reg = resolve_regulatory_status(db, standard.id)
            regulatory_by_standard[standard.id] = reg
            node_id = f"standard:{standard.id}"
            node_ids.add(node_id)
            nodes.append(
                {
                    "id": node_id,
                    "type": "standard",
                    "standard_id": standard.id,
                    "label": _display_number(standard),
                    "title": standard.title,
                    "category": standard.product_category or "",
                    "regulatory": reg.status.value,
                    "is_demo": bool(standard.is_demo),
                    "clause_count": clauses_repo(db).count({"standard_id": standard.id}),
                    "requirement_count": requirements_repo(db).count(
                        {"standard_id": standard.id}
                    ),
                }
            )

        # ---- Standard -> standard edges ------------------------------------
        rel_edges = relationships_repo(db).find(
            {"source_standard_id": {"$in": list(standard_ids)}}
        )
        for edge in rel_edges:
            target_node = f"standard:{edge.target_standard_id}"
            if target_node not in node_ids:
                # The target is outside the current view (a category filter, or a
                # focus neighbourhood). Skip rather than draw a dangling edge.
                continue
            edges.append(
                {
                    "source": f"standard:{edge.source_standard_id}",
                    "target": target_node,
                    "type": edge.relationship_type,
                    "label": _rel_label(edge.relationship_type),
                    "evidence": edge.evidence,
                    "is_demo": _edge_is_demo(regulatory_by_standard, edge),
                }
            )

        # ---- QCO (regulatory) nodes + edges --------------------------------
        if include_regulatory:
            for standard in standards:
                reg = regulatory_by_standard[standard.id]
                if reg.status.value not in ("MANDATORY", "UPCOMING"):
                    continue
                qco_node = f"qco:{standard.id}"
                if qco_node not in node_ids:
                    node_ids.add(qco_node)
                    nodes.append(
                        {
                            "id": qco_node,
                            "type": "qco",
                            "label": reg.notification_number or "QCO",
                            "title": reg.qco_name or "Quality Control Order",
                            "regulatory": reg.status.value,
                            "is_demo": bool(reg.is_mock),
                            "ministry": reg.ministry or "",
                        }
                    )
                edges.append(
                    {
                        "source": f"standard:{standard.id}",
                        "target": qco_node,
                        "type": "regulated_by",
                        "label": _rel_label("regulated_by"),
                        "evidence": (
                            f"{reg.qco_name or 'A Quality Control Order'} "
                            f"({reg.notification_number or 'no number on file'}) "
                            f"makes conformity mandatory."
                        ),
                        "is_demo": bool(reg.is_mock),
                    }
                )

        legend = self._legend(edges)
        return {
            "nodes": nodes,
            "edges": edges,
            "categories": self._categories(db),
            "relationship_types": legend,
            "focus": f"standard:{focus}" if focus and f"standard:{focus}" in node_ids else "",
            "stats": {
                "standards": sum(1 for n in nodes if n["type"] == "standard"),
                "regulatory_nodes": sum(1 for n in nodes if n["type"] == "qco"),
                "edges": len(edges),
                "relationship_types": len(legend),
            },
            "available": bool(nodes),
            "note": (
                "Every node is a stored standard or regulatory record, and every edge is a "
                "stored relationship that cites the clause stating it. Nothing in this graph "
                "is generated by a language model."
            ),
        }

    # ------------------------------------------------------------------
    def _select_standards(
        self, db: Database, *, category: str, focus: str
    ) -> List[Standard]:
        if focus:
            root = standards_repo(db).get(focus)
            if root is None:
                return []
            # Focus + its one-hop neighbourhood (both directions).
            neighbour_ids: set[str] = {root.id}
            repo = relationships_repo(db)
            outgoing = repo.find({"source_standard_id": focus})
            incoming = repo.find({"target_standard_id": focus})
            for edge in outgoing:
                neighbour_ids.add(edge.target_standard_id)
            for edge in incoming:
                neighbour_ids.add(edge.source_standard_id)
            rows = standards_repo(db).find({"_id": {"$in": list(neighbour_ids)}})
            return sorted(rows, key=lambda s: (s.id != focus, s.is_number))

        filt = {"product_category": category} if category else {}
        return standards_repo(db).find(filt, sort=[("is_number", ASCENDING)])

    @staticmethod
    def _categories(db: Database) -> List[str]:
        values = standards_repo(db).distinct(
            "product_category", {"product_category": {"$ne": ""}}
        )
        return sorted({v for v in values if v})

    @staticmethod
    def _legend(edges: List[Dict[str, Any]]) -> List[Dict[str, str]]:
        present = []
        seen: set[str] = set()
        for edge in edges:
            if edge["type"] in seen:
                continue
            seen.add(edge["type"])
            meta = RELATIONSHIP_META.get(edge["type"], {})
            present.append(
                {
                    "type": edge["type"],
                    "label": meta.get("label", _rel_label(edge["type"])),
                    "description": meta.get("description", ""),
                }
            )
        return present


def _edge_is_demo(regulatory_by_standard: Dict[str, Any], edge: StandardRelationship) -> bool:
    """A relationship edge inherits the demo flag of its source standard."""
    reg = regulatory_by_standard.get(edge.source_standard_id)
    return bool(reg.is_mock) if reg is not None else True


_service: Optional[StandardsGraphService] = None


def get_graph_service() -> StandardsGraphService:
    global _service
    if _service is None:
        _service = StandardsGraphService()
    return _service
