"""LLMService - the single entry point every other service uses.

Responsibilities:

* pick a provider from environment configuration (or none at all),
* run structured JSON generation with one repair retry,
* validate the parsed payload against a Pydantic model,
* never raise into the request path - callers get ``None`` and fall back to
  their deterministic implementation.
"""
from __future__ import annotations

import logging
import os
from typing import Any, Dict, List, Optional, Type, TypeVar

from pydantic import BaseModel, ValidationError

from app.core.config import settings
from app.llm.base import LLMMessage, LLMProvider, LLMResult
from app.llm.providers import PROVIDERS, NullProvider, extract_json

logger = logging.getLogger(__name__)

T = TypeVar("T", bound=BaseModel)

#: Env vars checked when LLM_PROVIDER=auto, in priority order.
AUTO_KEYS = [
    ("openai", "OPENAI_API_KEY"),
    ("anthropic", "ANTHROPIC_API_KEY"),
    ("gemini", "GEMINI_API_KEY"),
    ("gemini", "GOOGLE_API_KEY"),
]


class LLMService:
    def __init__(self, provider: Optional[LLMProvider] = None) -> None:
        self.provider = provider or self._build_provider()
        self.last_error: Optional[str] = None

    # -- construction ----------------------------------------------------
    @staticmethod
    def _build_provider() -> LLMProvider:
        name = (settings.llm_provider or "auto").lower().strip()
        key = settings.llm_api_key.strip()

        if name in PROVIDERS and key:
            return PROVIDERS[name](key, settings.llm_model, settings.llm_timeout_seconds)

        if name == "auto" or not key:
            for provider_name, env_var in AUTO_KEYS:
                env_key = os.getenv(env_var, "").strip()
                if env_key:
                    return PROVIDERS[provider_name](
                        env_key, settings.llm_model, settings.llm_timeout_seconds
                    )
            if key and name in PROVIDERS:
                return PROVIDERS[name](key, settings.llm_model, settings.llm_timeout_seconds)
        return NullProvider()

    # -- introspection ---------------------------------------------------
    @property
    def available(self) -> bool:
        return self.provider.available

    @property
    def provider_name(self) -> str:
        return self.provider.name

    @property
    def model_name(self) -> str:
        return self.provider.model or getattr(self.provider, "default_model", "")

    def status(self) -> Dict[str, Any]:
        return {
            "available": self.available,
            "mode": self.mode,
            "provider": self.provider_name,
            "model": self.model_name if self.available else None,
            "fallback_mode": not self.available,
            "supported_providers": sorted(PROVIDERS.keys()),
            "last_error": self.last_error,
            "note": (
                "AI + Retrieval: answers are generated by the language model from "
                "retrieved clause text, and every claim is validated against that "
                "evidence before it is shown."
                if self.available
                else "Retrieval-only: no LLM key is configured. Clause text is quoted "
                     "verbatim instead of paraphrased. Search, clause retrieval, "
                     "regulatory lookup and gap analysis are unaffected - the model "
                     "was never the source of those answers."
            ),
        }

    @property
    def mode(self) -> str:
        """The label shown throughout the UI."""
        return "AI + Retrieval" if self.available else "Retrieval-only"

    # -- generation ------------------------------------------------------
    def text(self, system: str, prompt: str, *, temperature: float = 0.2,
             max_tokens: int = 1200) -> Optional[str]:
        if not self.available:
            return None
        result: LLMResult = self.provider.generate(
            system, [LLMMessage("user", prompt)],
            temperature=temperature, max_tokens=max_tokens,
        )
        if not result.ok:
            self.last_error = result.error
            return None
        return result.text.strip()

    def structured(
        self,
        system: str,
        prompt: str,
        model: Type[T],
        *,
        temperature: float = 0.0,
        max_tokens: int = 1600,
        retries: int = 1,
    ) -> Optional[T]:
        """Generate JSON and validate it against ``model``.

        Returns ``None`` when the provider is missing, errors, or cannot be
        coerced into the schema after ``retries`` repair attempts.
        """
        if not self.available:
            return None

        schema_hint = _schema_hint(model)
        full_system = (
            system
            + "\n\nReturn ONLY a JSON object matching this schema (no prose, no markdown):\n"
            + schema_hint
        )
        messages: List[LLMMessage] = [LLMMessage("user", prompt)]

        for attempt in range(retries + 1):
            result = self.provider.generate(
                full_system, messages, json_mode=True,
                temperature=temperature, max_tokens=max_tokens,
            )
            if not result.ok:
                self.last_error = result.error
                return None
            try:
                payload = extract_json(result.text)
                return model.model_validate(payload)
            except (ValueError, ValidationError) as exc:
                self.last_error = str(exc)
                logger.info("LLM structured output invalid (attempt %s): %s", attempt + 1, exc)
                if attempt >= retries:
                    return None
                messages = [
                    LLMMessage("user", prompt),
                    LLMMessage("assistant", result.text[:2000]),
                    LLMMessage(
                        "user",
                        "That output was not valid for the schema. Error:\n"
                        f"{str(exc)[:800]}\nReturn corrected JSON only.",
                    ),
                ]
        return None


def _schema_hint(model: Type[BaseModel]) -> str:
    import json

    schema = model.model_json_schema()
    schema.pop("title", None)
    return json.dumps(schema, indent=2)[:4000]


_service: Optional[LLMService] = None


def get_llm() -> LLMService:
    global _service
    if _service is None:
        _service = LLMService()
    return _service


def reset_llm(service: Optional[LLMService] = None) -> None:
    """Test hook."""
    global _service
    _service = service
