"""Corpus-wide standards knowledge graph.

The graph must be *derived from stored records only*: every node a standard or
regulatory row, every edge a stored relationship. These tests pin that down so
the graph can never quietly start inventing connections.
"""
from __future__ import annotations

from app.services.graph import get_graph_service


def test_graph_endpoint_returns_standards_and_relationship_edges(client):
    body = client.get("/api/standards/graph").json()

    assert body["available"] is True
    standard_nodes = [n for n in body["nodes"] if n["type"] == "standard"]
    assert len(standard_nodes) >= 8, "the demo corpus has at least eight standards"

    # Every edge points at nodes that are actually in the graph.
    node_ids = {n["id"] for n in body["nodes"]}
    for edge in body["edges"]:
        assert edge["source"] in node_ids
        assert edge["target"] in node_ids

    # The known normative reference from DEMO-STD-001 to DEMO-STD-003 is present.
    assert any(
        e["source"] == "standard:DEMO-STD-001"
        and e["target"] == "standard:DEMO-STD-003"
        and e["type"] == "references_test_method"
        for e in body["edges"]
    )


def test_every_edge_type_is_in_the_legend(client):
    body = client.get("/api/standards/graph").json()
    legend_types = {row["type"] for row in body["relationship_types"]}
    edge_types = {e["type"] for e in body["edges"]}
    assert edge_types.issubset(legend_types)
    # The legend carries a human label and an explanation, not just a slug.
    for row in body["relationship_types"]:
        assert row["label"] and row["label"] != row["type"] or row["description"]


def test_mandatory_standards_get_a_regulatory_node(client):
    body = client.get("/api/standards/graph").json()
    # DEMO-STD-001 is MANDATORY in the seed, so it must have a regulated_by edge.
    assert any(
        e["source"] == "standard:DEMO-STD-001" and e["type"] == "regulated_by"
        for e in body["edges"]
    )
    assert any(n["type"] == "qco" for n in body["nodes"])


def test_regulatory_can_be_excluded(client):
    body = client.get("/api/standards/graph?regulatory=false").json()
    assert all(n["type"] != "qco" for n in body["nodes"])
    assert all(e["type"] != "regulated_by" for e in body["edges"])


def test_category_filter_narrows_the_graph(db):
    graph = get_graph_service().build(db, category="electrical-appliance")
    assert graph["nodes"], "the electrical-appliance category should have standards"
    for node in graph["nodes"]:
        if node["type"] == "standard":
            assert node["category"] == "electrical-appliance"
    # No edge may point outside the filtered set.
    node_ids = {n["id"] for n in graph["nodes"]}
    for edge in graph["edges"]:
        assert edge["source"] in node_ids and edge["target"] in node_ids


def test_focus_returns_a_standard_and_its_neighbourhood(db):
    graph = get_graph_service().build(db, focus="DEMO-STD-001")
    assert graph["focus"] == "standard:DEMO-STD-001"
    standard_ids = {n["standard_id"] for n in graph["nodes"] if n["type"] == "standard"}
    assert "DEMO-STD-001" in standard_ids
    # DEMO-STD-001 references DEMO-STD-002/003/008 in the seed.
    assert {"DEMO-STD-002", "DEMO-STD-003"}.issubset(standard_ids)


def test_focus_on_unknown_standard_is_empty_not_an_error(db):
    graph = get_graph_service().build(db, focus="NO-SUCH-STD")
    assert graph["available"] is False
    assert graph["nodes"] == []


def test_graph_carries_a_provenance_note(client):
    body = client.get("/api/standards/graph").json()
    assert "generated by a language model" in body["note"]
    # Demo standards are flagged as such, never presented as verified.
    assert all("is_demo" in n for n in body["nodes"] if n["type"] == "standard")


def test_graph_is_not_shadowed_by_the_standard_detail_route(client):
    """'graph' must resolve to the graph, not be read as a standard id."""
    assert client.get("/api/standards/graph").status_code == 200
